version: "3.8"
services:
  dockge:
    image: louislam/dockge:latest
    restart: always
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/dockge/data:/app/data
      - /root/dockge/stacks:/root/dockge/stacks
    environment:
      - DOCKGE_STACKS_DIR=/root/dockge/stacks
