version: "3"
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    user: root
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_PORT=5678
    volumes:
      - ${DATA_FOLDER}/.n8n:/home/node/.n8n
      - ${LOCAL_FILES}:/files
networks: {}
