version: "3"
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    user: root
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_PORT=5678
    volumes:
      - ${DATA_FOLDER}/.n8n:/home/node/.n8n
      - ${LOCAL_FILES}:/files
networks: {}
#if you hae error to accesss /home/node ...
#stop compose the run this command below
#docker run -it --rm -v n8n_data:/home/data bash chown 1000:100 -R home/data
#then start docker agian
