version: "3.3"
services:
  n8n:
    container_name: n8n
    ports:
      - 5678:5678
    volumes:
      - /docker/n8n/n8n_data:/home/node/.n8n
    image: docker.n8n.io/n8nio/n8n
volumes:
  n8n_data: {}
networks: {}
