version: "3"
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: file-browser
    ports:
      - 81:80
    volumes:
      - /:/srv
# mkdir -p /docker/filebrowser/config && touch /docker/filebrowser/config/filebrowser.db
      - /docker/file-browser/config/filebrowser.db:/database.db
    restart: always
