version: "3.3"
services:
  uptime-kuma:
    restart: always
    ports:
      - 3001:3001
    volumes:
      - /docker/uptime-kuma:/app/data
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    environment:
      - UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true
networks: {}
